# -*- coding: utf-8 -*-
"""Capstone example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cre_OlBYN_XAxfY7VzuB46_B_qYweGI0

## **This notebook will be mainly used for the capstone project in the Coursera IBM data science certificate.**
"""

import pandas as pd
import numpy as np

print("Hello Capstone Project Course!")

